### ISSUE TITLE
Interaction terms

### ISSUE THREAD

**Issue by Hoeze** [jzluo/firthlogist#16]
Hi, I would like to test the significance of a variable with an interaction term as covariate:
`trait ~ sex:age + variable_to_test`
Can I do this with your library @jzluo?

**Comment by jzluo** [comment]
Hi @Hoeze, this would have to done in the data preparation just like sklearn. Say you have a dataframe `df` with columns `trait, sex, age, variable_to_test`. Two simple examples:

- Use [patsy](https://patsy.readthedocs.io/en/latest/API-reference.html#patsy.dmatrices)
```python
y, X = dmatrices('trait ~ sex:age + variable_to_test', df)
```
- Create interaction term in pandas
```python
df['sex:age'] = df['sex'] * df['age']
X, y = df[['sex:age', 'variable_to_test']], df['trait']
```

Let me know if it works for you!
